modLoader = "javafml"
loaderVersion = "[43,)"
license = "Apache License 2.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile="logo.png"
description = "${mod_description}"
authors = "The Realm 18 Studios, TheRealM18"
displayURL = "${mod_url}"

[[dependencies.tr18sgi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.tr18sgi]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tr18sgi]]
modId = "gtceu"
mandatory = true
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"